const medicine = {
  nrti: [
    {
      name: "Efavirenz 600mg",
      brand: "Efavir",
      commonDose: "ONE (1) tablet ONCE daily",
      beforeAfter: "Empty stomach",
      dayNight: "Night",
      adjustmentRenal: "No dosage adjustment",
      adjustmentLiverMild: "No dosage adjustment",
      adjustmentLiverModerate: "Not recommended",
      adjustmentLiverSevere: "Not recommended",
      crushed: "Yes",
      crushInstruction: "Tablets can be divided ",
      pregancy: "Yes",
      sideEffects:
        "Diarrhoea, vomiting, abdominal pain, bloating, flatulence, heartburn and indigestion, loss of appetite.\nNausea, headache, dizziness, sinus or throat infections.\nPancreatitis,  diabetes, high blood pressure, tiredness, difficulty in sleeping,  anxiety, haemorrhoids.\nRash, itching, skin infections, lipodystrophy (changes to fat distribution in body), weakness\nAllergic reaction including swelling, infections in the respiratory tract, cough, sore throat, runny nose, erectile dysfunction, menstrual disorders, peripheral nerve damage, muscle pain.",
      monitoring:
        "Blood sugar\nChanges in heart rhythm\nLiver enzyme\nLipid levels",
      population: "none",
      takenMed: "none",
      notTakenMed: "Ergotamine\nMidazolam\nPhenytoin",
      interaction:
        "Atorvastatin\nAtovaquone/proguanil\nBupropion\nCarbamazepine\nClarithromycin\nCyclosporine\nDiltiazem\nItraconazole\nMethadone\nPhenobarbital\nPhenytoin\nPravastatin\nRifabutin\nRifampicin\nSertraline\nSimvastatin\nSirolimus\nTacrolimus\nVoriconazole\nWarfarin\nGinkgo biloba",
      doseInstrcution:
        "https://www.aidsmap.com/about-hiv/a-z-antiretroviral-medications",
      crushInstructionLink:
        "https://liverpool-hiv-hep.s3.amazonaws.com/prescribing_resources/pdfs/000/000/011/original/ARV_Swallowing_2018_Oct.pdf?1540371581#:~:text=Lamivudine\n20Epivir\n20Tablets\n20can\n20be,or\n20liquid\n20and\n20taken\n20immediately.&text=Dosing\n20is\n20the\n20same\n20for\n20oral\n20solution\n20and\n20tablets.,-\nE2\n80\nA2",
      image: require("../assets/img/efavir.png"),
      category: 1,
      id: 0,
    },
    {
      name: "Nevirapine 200mg",
      brand: "Hirapine / Nevirapine",
      commonDose: "TWO (2) tablets ONCE daily or ONE (1) tablet TWICE daily",
      beforeAfter: "With/without food",
      dayNight: "Any",
      adjustmentRenal: "No dosage adjustment",
      adjustmentLiverMild: "No dosage adjustment",
      adjustmentLiverModerate: "Not recommended",
      adjustmentLiverSevere: "Not recommended",
      crushed: "Yes",
      crushInstruction:
        "Crush tablets and dissolved in water (for twice daily dosages only) ",
      pregancy: "Yes (if CD4 > 250 cell/mm3)",
      sideEffects:
        "Rash, allergic reaction, fatigue and fever, blisters, sores in the mouth, eye inflammation, facial or other swelling, difficulty breathing, muscle or joint pain, generally feeling ill\nHeadache, nausea, vomiting, abdominal pain, diarrhoea, loss of appetite and pain, aching or sensitivity on the right side of your body\nRaised liver enzymes, raised blood pressure\nYellowing of the skin or whites of the eyes (jaundice), dark or tea-coloured urine, pale-coloured stools.",
      monitoring:
        "First 18 weeks of initiating therapy - Liver enzymes\nSevere rash (Stevens Johnson syndrome)",
      population: "Men: CD4 < 400 cells/mm3\nWomen: CD4 < 250 cells/mm3 ",
      takenMed: "none",
      notTakenMed: " St John's wort",
      interaction:
        "Atazanavir\nClarithromycin\nEfavirenz\nLopinavir / ritonavir\nMethadone \nRifampicin\nRifabutin\nWarfarin\nAnti-fungal medicines\nHormonal contraceptives",
      doseInstrcution: "",
      crushInstructionLink: "",
      image: require("../assets/img/hirapine.png"),
      category: 1,
      id: 1,
    },
  ],
  pi: [
    {
      name: "Lopinavir 200mg / Ritonavir 50mg",
      brand: "Kaletra",
      commonDose: "TWO (2) tablets TWICE daily or FOUR (4) tablets ONCE daily",
      beforeAfter: "With food",
      dayNight: "Any",
      adjustmentRenal: "No dosage adjustment",
      adjustmentLiverMild: "No dosage adjustment",
      adjustmentLiverModerate: "No dosage adjustment",
      adjustmentLiverSevere: "No dosage adjustment",
      crushed: "Yes",
      crushInstruction:
        "Kaletra syrup is available as an alternative if a smaller dose is required",
      pregancy:
        "Continuation of treatment. Not for newly diagnosed patients.\nNot in combination with Emtricitabine 200mg +Tenofovir 300mg",
      sideEffects:
        "Diarrhoea, vomiting, abdominal pain, bloating, flatulence, heartburn and indigestion, loss of appetite.\nNausea, headache, dizziness, sinus or throat infections.\nPancreatitis,  diabetes, high blood pressure, tiredness, difficulty in sleeping,  anxiety, haemorrhoids.\nRash, itching, skin infections, lipodystrophy (changes to fat distribution in body), weakness\nAllergic reaction including swelling, infections in the respiratory tract, cough, sore throat, runny nose, erectile dysfunction, menstrual disorders, peripheral nerve damage, muscle pain.",
      monitoring:
        "Blood sugar\nChanges in heart rhythm\nLiver enzymes\nLipid levels",
      population: "none",
      takenMed: "none",
      notTakenMed:
        "Alcohol\nAlfuzosin\nAmiodarone\nColchicine\nDonedarone\nErgotamine\nFusidic acid\nMidazolam \nQuetiapine\nRanolazine\nSildenafil\nSimvastatin\nVardenafil",
      interaction:
        "Acyclovir-Valacyclovir\nClarithromycin\nClozapine\nDeferiprone\nDoxorubicin\nFluconazole\nGanciclovir-Valganciclovir\nMethadone\nRaltegravir\nRibavirin\nTrimethoprim\nMedications for epilepsy (e.g.,Valporate products)",
      doseInstrcution: "",
      crushInstructionLink: "",
      image: require("../assets/img/kaletra.png"),
      category: 2,
      id: 2,
    },
    {
      name: "Ritonavir 100mg",
      brand: "Norvir",
      commonDose: "ONE (1) / TWO (2) capsule ONCE / TWICE daily",
      beforeAfter: "With food",
      dayNight: "Any",
      adjustmentRenal: "No dosage adjustment",
      adjustmentLiverMild: "No dosage adjustment",
      adjustmentLiverModerate: "No dosage adjustment",
      adjustmentLiverSevere: "Not recommended",
      crushed: "No",
      crushInstruction: "",
      pregancy: "Yes",
      sideEffects:
        "Raised lipid & liver enzymes, liver toxicity, nausea, vomiting, diarrhoea, abdominal pain, headache, diabetes\nChanges in heart rhythm, severe allergic (hypersensitivity) reaction and rash (Stevens-Johnson syndrome).",
      monitoring: "Blood sugar\nLipid levels\nLiver enzymes \nSerum lipase",
      population: "none",
      takenMed: "none",
      notTakenMed:
        "Alfuzosin\nAmiodarone\nColchicine\nDiazepam\nDronedarone\nFlecanaide\nFusidic acid\nMidazolam\nQuetiapine\nRanolazine\nSildenafil \nSimvastatin\nVardenafil",
      interaction:
        "Anticoagulants\nAsthma (steroid-containing inhalers)\nAllergy medications\nCalcium channel blockers\nChemotherapy drugs (some)\nH2 receptors\nProton pump inhibitors \nAnti-fungal\nAnticonvulsants\nImmunosuppressants\nNasal sprays (steroid-containing sprays)\nEye drops (steroid-containing drops)\nHormonal contraceptives",
      doseInstrcution: "",
      crushInstructionLink: "",
      image: require("../assets/img/norvir.png"),
      category: 2,
      id: 3,
    },
    {
      name: "Atazanavir 300mg",
      brand: "Atazor / Atazanavir/ Reyataz",
      commonDose: "ONE (1) tablet ONCE daily",
      beforeAfter: "With food",
      dayNight: "Any",
      adjustmentRenal: "No dosage adjustment",
      adjustmentLiverMild: "Dose adjustment required",
      adjustmentLiverModerate: "Dose adjustment required",
      adjustmentLiverSevere: "Not recommended",
      crushed: "No",
      crushInstruction: "",
      pregancy: "Continuation of treatment. Not for newly diagnosed patients",
      sideEffects:
        "Headache, rash, tiredness\nFeeling / being sick (nausea, vomiting) diarrhoea, abdominal pain, indigestion\nRaised billirubin level (jaundice)",
      monitoring: "Blood sugar\nChanges in heart rhythm\nLiver enzymes",
      population: "none",
      takenMed: "Ritonavir: ONE (1) tablet (100mg) ONCE daily  ",
      notTakenMed:
        "Ergotamine\nMidazolam\nProton pump inhibitor (dexlansoprazole, esomeprazole, lansoprazole, omeprazole, pantoprazole) rabeprazole, \nQuetiapine\nRifampicin\nSildenafil\nSimvastatin",
      interaction:
        "Antacids\nAntidiabetic agents\nChemotherapy agents\nImmunomodulators\nMedications that are classed as CYP3A4 Inhibitors",
      doseInstrcution: "",
      crushInstructionLink: "",
      image: require("../assets/img/atazor.png"),
      category: 2,
      id: 4,
    },
    {
      name: "Darunavir 600mg",
      brand: "Prezista",
      commonDose: "ONE (1) tablet TWICE daily",
      beforeAfter: "With food (Take with a snack to assist absorption of drug)",
      dayNight: "Any",
      adjustmentRenal: "No dosage adjustment",
      adjustmentLiverMild: "No dosage adjustment",
      adjustmentLiverModerate: "Dose adjustment required",
      adjustmentLiverSevere: "Not recommended",
      crushed: "Yes",
      crushInstruction: "Mix with semi solid / liquid and taken immediately",
      pregancy: "Yes",
      sideEffects:
        "Diarrhoea, vomiting, nausea, abdominal pain, indigestion, bloating, flatulence.\nHeadache, tiredness, dizziness, drowsiness, numbness, peripheral neuropathy (tingling or pain at hands/feet), difficulty in sleeping, weakness.\nRash, itching, diabetes, raised lipids, raised liver enzymes \nLipodystrophy (changes to fat distribution in body), fever",
      monitoring: "Blood sugar\nLiver enzymes",
      population: " CD4 > 200 cells/mm3",
      takenMed: "Ritonavir: ONE (1) tablet (100mg) TWICE daily  ",
      notTakenMed:
        "Alfuzosin\nAmiodarone\nColchicine\nErgotamine\nLopinavir/ritonavir (Kaletra)\nMetformin\nMidazolam\nQuetiapine\nRanolazine\nRifampacin\nSildenafil\nSimvastatin\nTicagrelor",
      interaction:
        "Antibiotics\nCorticosteroids\nHormonal contraceptives\nMetformin\nMethadone \nStatins",
      doseInstrcution: "",
      crushInstructionLink: "",
      image: require("../assets/img/atazor.png"),
      category: 2,
      id: 5,
    },
  ],
  nnrti: [
    {
      name: "Emtricitabine 200mg / Tenofovir 300mg",
      brand: "Tenof-EM / Truvada",
      commonDose: "ONE (1) tablet ONCE daily",
      beforeAfter: "With food",
      dayNight: "Any",
      adjustmentRenal: "CrCl ≤50 mL/minute:  Dosage adjustment necessary",
      adjustmentLiverMild: "No dosage adjustment",
      adjustmentLiverModerate: "No dosage adjustment",
      adjustmentLiverSevere: "No dosage adjustment",
      crushed: "Yes",
      crushInstruction:
        "Crushed in 100ml water / orange juice and taken immediately",
      pregancy: "Yes",
      sideEffects:
        "Diarrhoea, flatulence, stomach pain or bloating, feeling / being sick (nausea / vomiting)\nDizziness, headache \nRash, feeling weak (fatigue), pain  \nDifficulty sleeping, abnormal dreams\nSkin darkening \nAllergic reactions, such as wheezing, swelling or feeling light-headed.",
      monitoring:
        "Bone mineral density (BMD)\nHepatitis B virus (before initiation of treatment)\nKidney enzymes \nLiver enzymes",
      population: "none",
      takenMed: "none",
      notTakenMed: "Tenofovir alafenamide\nLamivudine\nAdefovir dipivoxil",
      interaction:
        "Aminoglycosides\nAmphotericin B\nFoscarnet Ganciclovir\nPentamidine\nVancomycin Interleukin-2 \nNon-steroidal anti-inflammatory drugs",
      doseInstrcution: "",
      crushInstructionLink: "",
      image: require("../assets/img/tenof.png"),
      category: 3,
      id: 6,
    },
    {
      name: "Lamivudine 150mg / Zidovudine 300mg",
      brand: "Lamizido / Combivir",
      commonDose: "ONE (1) tablet TWICE daily",
      beforeAfter: "With/without food",
      dayNight: "Any",
      adjustmentRenal: "CrCl <50 mL/minute: Not recommended",
      adjustmentLiverMild: "Not recommended",
      adjustmentLiverModerate: "Not recommended",
      adjustmentLiverSevere: "Not recommended",
      crushed: "Yes",
      crushInstruction:
        "Mix with semi solid / liquid (approx 15 minutes) and taken immediately",
      pregancy: "Yes",
      sideEffects:
        "Nausea, headache, vomiting, fatigue, diziness, weakness, muscle pain, fever\nDiarrhoea, abdominal pain, loss of appetite\nTiredness, insomnia (difficulty sleeping), joint or muscle pain, cough, runny nose, hair loss, rash, fat loss, anaemia, low white blood cell count, raised liver enzymes.",
      monitoring:
        "Blood disorders\nBone mineral density (BMD)\nKidney enzyme\nLipodystrophy (changes to fat distribution in body)\nMuscle enzymes (signs of muscle weakness / pain)",
      population: "none",
      takenMed: "none",
      notTakenMed:
        "Clabribine\nCotrimoxazole (high dose)\nEmtricitabine\nGanciclovir\nLamivudine\nRibavirin.",
      interaction:
        "Antibiotics\nAntiepilepsy drugs\nAnti-malaria \nChemotherapy drugs\nMedications for gout\nMethadone",
      doseInstrcution: "",
      crushInstructionLink: "",
      image: require("../assets/img/atazor.png"),
      category: 3,
      id: 7,
    },
    {
      name: "Lamivudine 150mg",
      brand: "Valfix / Lamivox",
      commonDose: "TWO (2) tablets ONCE daily or ONE (1) tablet TWICE daily",
      beforeAfter: "With/without food",
      dayNight: "Any",
      adjustmentRenal: "CrCl ≥50 mL/minute: No dosage adjustment",
      adjustmentLiverMild: "No dosage adjustment ",
      adjustmentLiverModerate: "No dosage adjustment ",
      adjustmentLiverSevere: "No dosage adjustment ",
      crushed: "Yes",
      crushInstruction:
        "Mix with semi solid / liquid (approx 15 minutes) and taken immediately",
      pregancy: "Yes",
      sideEffects:
        "Headache, fatigue (tiredness / lack of energy), feeling / being sick (nausea, vomiting)\nDecreased appetite, diarrhoea, skin rash and abdominal pain\nFever (high temperature), general feeling of being unwell, muscle pain and discomfort, joint pain, difficulty in sleeping (insomnia), cough, irritated or runny nose, hair loss (alopecia).",
      monitoring: "Liver enzymes\nMuscle enzymes",
      population: "none",
      takenMed: "none",
      notTakenMed: "Emtricitabine\nCotrimoxazole (high dose)\nCladribine",
      interaction: "Orlistat \nTrimethoprim",
      doseInstrcution: "",
      crushInstructionLink: "",
      image: require("../assets/img/atazor.png"),
      category: 3,
      id: 8,
    },
    {
      name: "Abacavir 300mg",
      brand: "Ziagen",
      commonDose: "TWO (2) tablets ONCE daily or ONE (1) tablet TWICE daily",
      beforeAfter: "With/without food",
      dayNight: "Any",
      adjustmentRenal: "CrCl ≥50 mL/minute: No dosage adjustment",
      adjustmentLiverMild: "Dose adjustment required",
      adjustmentLiverModerate: "Not recommended",
      adjustmentLiverSevere: "Not recommended",
      crushed: "Yes",
      crushInstruction: "Mix with semi solid / liquid and taken immediately",
      pregancy: "Yes(If HLA-B5701 is negative)",
      sideEffects:
        "Feeling sick (nausea / vomiting), headache, diarrhoea, loss of appetite, abdominal pain\nTiredness, lack of energy, fever, skin rash, shortness of breath, sore throat, cough",
      monitoring: "HLA-B*5701  status",
      population: "none",
      takenMed: "none",
      notTakenMed:
        "Emtricitabine\nLamivudine\nTrimethoprim/sulfamethoxazole (high dose)\nCladribine",
      interaction: "Phenytoin\nMethadone",
      doseInstrcution: "",
      crushInstructionLink: "",
      image: require("../assets/img/ziagen.png"),
      category: 3,
      id: 9,
    },
    {
      name: "Abacavir 600mg / Lamivudine 300mg",
      brand: "Kivexa",
      commonDose: "ONE (1) tablet ONCE daily",
      beforeAfter: "With/without food",
      dayNight: "Any",
      adjustmentRenal: "CrCl <50 mL/minute: Not recommended",
      adjustmentLiverMild: "Not recommended",
      adjustmentLiverModerate: "Not recommended",
      adjustmentLiverSevere: "Not recommended",
      crushed: "No",
      crushInstruction: "",
      pregancy: "No",
      sideEffects:
        "Hypersensitivity reaction, cough, irritated or runny nose, skin rash, sore throat\nHeadache, fever, general feeling of being unwell, difficulty sleeping\nDiarrhoea, feeling sick (nausea /vomiting), stomach pains, loss of appetite, \nTiredness, lack of energy, muscle & joint pain and discomfort, hair loss (alopecia), shortness of breath",
      monitoring:
        "HLA-B*5701  status\nBlood sugar\nKidney enzymes\nLiver enzymes ",
      population: "none",
      takenMed: "none",
      notTakenMed:
        "Emtricitabine\nLamivudine\nTrimethoprim/sulfamethoxazole (high dose)\nCladribine",
      interaction: "Phenytoin\nMethadone",
      doseInstrcution: "",
      crushInstructionLink: "",
      image: require("../assets/img/kivexa.png"),
      category: 3,
      id: 10,
    },
  ],
  nnnrti: [
    {
      name: "Tenofovir 300mg / Emtricitabine 200mg / Efavirenz 600mg",
      brand: "Viraday",
      commonDose: "ONE (1) tablet ONCE daily",
      beforeAfter: "Without food",
      dayNight: "Night",
      adjustmentRenal: "CrCl <50 mL/minute: Not recommended",
      adjustmentLiverMild: "No dosage adjustment",
      adjustmentLiverModerate: "Not recommended",
      adjustmentLiverSevere: "Not recommended",
      crushed: "No",
      crushInstruction: "",
      pregancy: "Continuation of treatment. Not for newly diagnosed patients",
      sideEffects:
        "Dizziness, headache, difficulty sleeping, abnormal dreams, difficulty concentrating, drowsiness, weakness.\nFeeling / being sick (nausea / vomitting), diarrhoea, stomach pains, feeling bloated, flatulence.\nSkin rash, allergic reaction, dark skin patches (often starting on the hands or soles of feet).\nSuicidal thoughts, anxious, depressed, paranoia and mood changes",
      monitoring:
        "Hepatitis B virus (2 weeks after initiation)\nKidney enzymes\nLipid level\nLiver enzymes",
      population: "none",
      takenMed: "none",
      notTakenMed: "St Johns Wort\nGinkgo biloba",
      interaction:
        "Antibiotics\nAntiepileptic \nAnticoagulants \nAntidepressants\nContraceptives\nMedication for high blood pressure\nMedication to lower cholesterol (e.g. statins)\nMethadone\nSt Johns Wort\nGinkgo biloba ",
      doseInstrcution: "",
      crushInstructionLink: "",
      image: require("../assets/img/viraday.png"),
      category: 4,
      id: 11,
    },
  ],
  ii: [
    {
      name: "Raltegravir 400mg",
      brand: "Isentress",
      commonDose: "ONE (1) tablet TWICE daily",
      beforeAfter: "With/without food",
      dayNight: "Any",
      adjustmentRenal: "No dosage adjustment",
      adjustmentLiverMild: "No dosage adjustment",
      adjustmentLiverModerate: "Not recommended",
      adjustmentLiverSevere: "Not recommended",
      crushed: "Yes",
      crushInstruction: "",
      pregancy: "Yes",
      sideEffects:
        "Loss of appetite, abdominal pain, bloating, flatulence, diarrhoea, nausea, vomiting, indigestion \nHeadache, dizziness, vertigo \nDifficulty sleeping, abnormal dreams, depression\nRash, hypersensitivity (allergic), weakness, fatigue, fever",
      monitoring: "Depression\nLipid level\nLiver enzymes \nSigns of skin rash",
      population: "none",
      takenMed: "none",
      notTakenMed: "No data",
      interaction:
        "Antacid\nMultivitamins, mineral supplements and antacids (taken 6 hours before or 2 hours after raltegravir)\nRifampicin",
      doseInstrcution: "",
      crushInstructionLink: "",
      image: require("../assets/img/isentress.png"),
      category: 5,
      id: 12,
    },
    {
      name: "Dolutegravir 50mg",
      brand: "Tivicay",
      commonDose: "ONE (1) tablet ONCE / TWICE daily ",
      beforeAfter: "With/without food",
      dayNight: "Any",
      adjustmentRenal: "No dosage adjustment",
      adjustmentLiverMild: "No dosage adjustment",
      adjustmentLiverModerate: "No dosage adjustment",
      adjustmentLiverSevere: "Not recommended",
      crushed: "Yes",
      crushInstruction: "Mix with semi solid / liquid and taken immediately",
      pregancy: "Yes",
      sideEffects:
        "Headache, insomnia (difficulty sleeping), dizziness, abnormal dreams, depression, lack of energy (fatigue).\nDiarrhoea, feeling sick (nausea), vomiting, abdominal pain or discomfort, wind (flatulence).\nRash, itching.\nWeight gain",
      monitoring:
        "Allergic reaction\nLiver enzymes\nMuscle enzymes\nPregnancy test (women - before treatment)",
      population: "none",
      takenMed: "none",
      notTakenMed: "No data",
      interaction:
        "Carbamazepine\nOxcarbazepine\nMetformin (Max: 1g daily)\nPhenobarbital\nPhenytoin\nRifampicin\nMultivitamins, mineral supplements and antacids (taken 6 hours before or 2 hours after dolutegravir)",
      doseInstrcution: "",
      crushInstructionLink: "",
      image: require("../assets/img/tivicay.png"),
      category: 5,
      id: 13,
    },
    {
      name: "Darunavir 600mg",
      brand: "Prezista",
      commonDose: "ONE (1) tablet TWICE daily",
      beforeAfter: "With food (Take with a snack to assist absorption of drug)",
      dayNight: "Any",
      adjustmentRenal: "No dosage adjustment",
      adjustmentLiverMild: "No dosage adjustment",
      adjustmentLiverModerate: "No dosage adjustment",
      adjustmentLiverSevere: "Not recommended",
      crushed: "Yes",
      crushInstruction: "Mix with semi solid / liquid and taken immediately",
      pregancy: "Yes",
      sideEffects:
        "Diarrhoea, vomiting, nausea, abdominal pain, indigestion, bloating, flatulence.\nHeadache, tiredness, dizziness, drowsiness, numbness, peripheral neuropathy (tingling or pain at hands/feet), difficulty in sleeping, weakness.\nRash, itching, diabetes, raised lipids, raised liver enzymes \nLipodystrophy (changes to fat distribution in body), fever",
      monitoring: "Blood sugar\nLiver enzymes",
      population: " CD4 > 200 cells/mm3",
      takenMed: "Ritonavir: ONE (1) tablet (100mg) TWICE daily  ",
      notTakenMed:
        "Alfuzosin\nAmiodarone\nColchicine\nErgotamine\nLopinavir/ritonavir (Kaletra)\nMetformin\nMidazolam\nQuetiapine\nRanolazine\nRifampacin\nSildenafil\nSimvastatin\nTicagrelor",
      interaction:
        "Antibiotics\nCorticosteroids\nHormonal contraceptives\nMetformin\nMethadone \nStatins",
      doseInstrcution: "",
      crushInstructionLink: "",
      image: require("../assets/img/isentress.png"),
      category: 5,
      id: 14,
    },
  ],
};

export default medicine;
